export { Avatar } from "./Avatar/Avatar";
export { AddPhoto } from "./AddPhoto/AddPhoto";
export { Button } from "./Buttons/Button/Button";
export { ButtonIcon } from "./Buttons/ButtonIcon/ButtonIcon";
export { ButtonRound } from "./Buttons/ButtonPlus/ButtonRound";
export { Input } from "./Input/Input";
export { Link } from "./Link/Link";
export { Title } from "./Title/Title";
export { Wallpaper } from "./Wallpaper/Wallpaper";
